# Import the Flaskavel application instance from the bootstrap.app module.
from bootstrap.app import app

def wsgi_handler(environ, start_response):
    """
    WSGI handler function to bridge between the web server and the Flaskavel application.

    Args:
        environ (dict): A dictionary containing the WSGI environment variables.
        start_response (callable): A callable to start the HTTP response.

    Returns:
        Callable: The response generated by the Flaskavel application's WSGI interface.
    """
    return app().handleRequest().wsgi_app(environ, start_response)
